[package]
name = "kids-bank-sam"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

lambda_runtime = "0.13.0"
aws-sdk-config = "1.47.0"
aws-sdk-dynamodb = "1.49.0"
serde = "1.0.210"
tokio = { version = "1", features = ["macros"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["fmt"] }
kids-bank-lib = { path = "../../kids-bank-lib" }
