PUT https://{{$dotenv API_ID}}.execute-api.{{$dotenv REGION}}.amazonaws.com/{{$dotenv STAGE}}/create
content-type: application/json

{
    "name": "test me",
    "email": "test@me.com",
    "password": "my-cool-pw"
}

###

POST https://{{$dotenv API_ID}}.execute-api.{{$dotenv REGION}}.amazonaws.com/{{$dotenv STAGE}}/login
content-type: application/json

{
  "email": "test@me.com",
  "password": "my-cool-pw"
}

###

GET https://{{$dotenv API_ID}}.execute-api.{{$dotenv REGION}}.amazonaws.com/{{$dotenv STAGE}}/account?id=testme_test@me.com
authorization: token
