PUT https://w3i1l95kwi.execute-api.us-east-1.amazonaws.com/create
content-type: application/json

{
    "name": "test me",
    "email": "test@me.com",
    "password": "my-cool-pw"
}

###

POST https://gwdhoxqazf.execute-api.us-east-1.amazonaws.com/dev/login
content-type: application/json

{
  "email": "test@me.com",
  "password": "my-cool-pw"
}

###

GET https://gwdhoxqazf.execute-api.us-east-1.amazonaws.com/dev/account?id=testme_test@me.com
authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0QG1lLmNvbSIsImV4cCI6MTczODE3MjM0MH0.SqF00Z6jd6Gce1tZJoA7qG5j9_j88XvA9BJzIMJBkj8
