PUT https://{api-id}.execute-api.us-east-1.amazonaws.com/create
content-type: application/json

{
    "name": "test me",
    "email": "test@me.com",
    "password": "my-cool-pw"
}

###

POST https://{api-id}.execute-api.us-east-1.amazonaws.com/dev/login
content-type: application/json

{
  "email": "test@me.com",
  "password": "my-cool-pw"
}

###

GET https://{api-id}.execute-api.us-east-1.amazonaws.com/dev/account?id=testme_test@me.com
authorization: token
